services:
  carla:
    image: carlasim/carla:0.9.10.1
    container_name: carla
    privileged: true
    runtime: nvidia 
    environment:
      - DISPLAY=${DISPLAY}   # Pass host DISPLAY variable
    network_mode: "host"      # Use host network
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 socket for GUI forwarding
    command: /bin/bash ./CarlaUE4.sh -opengl --world-port=2000
  carla2:
    image: carlasim/carla:0.9.10.1
    container_name: carla2
    privileged: true
    runtime: nvidia 
    environment:
      - DISPLAY=${DISPLAY}   # Pass host DISPLAY variable
    network_mode: "host"      # Use host network
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 socket for GUI forwarding
    command: /bin/bash ./CarlaUE4.sh -opengl --world-port=2002
  carla3:
    image: carlasim/carla:0.9.10.1
    container_name: carla3
    privileged: true
    runtime: nvidia 
    environment:
      - DISPLAY=${DISPLAY}   # Pass host DISPLAY variable
    network_mode: "host"      # Use host network
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 socket for GUI forwarding
    command: /bin/bash ./CarlaUE4.sh -opengl --world-port=2004
  carla4:
    image: carlasim/carla:0.9.10.1
    container_name: carla4
    privileged: true
    runtime: nvidia 
    environment:
      - DISPLAY=${DISPLAY}   # Pass host DISPLAY variable
    network_mode: "host"      # Use host network
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 socket for GUI forwarding
    command: /bin/bash ./CarlaUE4.sh -opengl --world-port=2006
